### ISSUE TITLE
doesn't work, doesn't terminate

### ISSUE THREAD

**Issue by ThomasWaldmann** [wolph/tissue#8]
nose==1.1.2
pep8==1.2
tissue==0.7

i ran "nosetests --with-tissue" from the toplevel directory of whoosh (search library).

but somehow nothing happens, no output, no error and it does not terminate either (I waited some minutes).

when I hit ctrl-c, i see this:

```
(env)tw@x300:~/w/whoosh$ nosetests --with-tissue 

^CTraceback (most recent call last):
  File "/home/tw/w/whoosh/env/bin/nosetests", line 9, in <module>
    load_entry_point('nose==1.1.2', 'console_scripts', 'nosetests')()
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/core.py", line 118, in __init__
    **extra_args)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/core.py", line 197, in runTests
    result = self.testRunner.run(self.test)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/core.py", line 61, in run
    test(result)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/suite.py", line 176, in __call__
    return self.run(*arg, **kw)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/suite.py", line 223, in run
    test(orig)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/suite.py", line 71, in run
    for test in self._tests:
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/suite.py", line 98, in _get_tests
    for test in self.test_generator:
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/loader.py", line 132, in loadTestsFromDir
    plugins.beforeDirectory(path)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/plugins/manager.py", line 94, in __call__
    return self.call(*arg, **kw)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/nose/plugins/manager.py", line 162, in simple
    result = meth(*arg, **kw)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/tissue.py", line 60, in beforeDirectory
    pep8.input_dir(path, runner=seen_runner)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/pep8.py", line 1370, in input_dir
    runner(os.path.join(root, filename))
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/tissue.py", line 59, in seen_runner
    pep8.input_file(filename)
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/pep8.py", line 1346, in input_file
    errors = Checker(filename).check_all()
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/pep8.py", line 1283, in check_all
    self.check_logical()
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/pep8.py", line 1220, in check_logical
    for result in self.run_check(check, argument_names):
  File "/home/tw/w/whoosh/env/local/lib/python2.7/site-packages/pep8.py", line 357, in whitespace_around_keywords
    for match in WHITESPACE_AROUND_KEYWORD_REGEX.finditer(logical_line):
KeyboardInterrupt
```

**Comment by ThomasWaldmann** [comment]
Note: i used pep8==1.2 because tissue did not work with the latest pep8.

**Comment by wolph** [comment]
This may have been a problem in the past but it's currently working for me.
